### ISSUE TITLE
Changes to website not reflected in code.

### ISSUE THREAD

**Issue by ghost** [Dinoosawruss/Automatic-Smart-Revise#1]
The smart revise website has recently changed in design so some of the XPATH's have changed, which have not been added to the code. I have fixed this and am happy to share the changed code with you.

**Comment by Dinoosawruss** [comment]
Ahh thanks!
I no longer have access to smart revise but feel free to submit a pull request with the changed code and I’ll take a look.

**Comment by ghost** [comment]
Have done, included comments in the Python as to where I changed things.

**Comment by Dinoosawruss** [comment]
PR merged 

Thanks for the help
